### ISSUE TITLE
[Question]: How to wait an async js function in go

### ISSUE THREAD

**Issue by Milerius** [teamortix/golang-wasm#9]
**Describe the bug:**
I Work with 2 wasm module, 1 written in rust, and one in golang, the rust one expose in the global javascript namespace few async js function and i would like to wait one of them from Golang, is that possible with this package ? 

Thanks a lot for your work

also the package is not working for me: panic: `JS wrapper __go_wasm__ is not an object`

**Comment by hhhapz** [comment]
Hey! Thanks for using Golang-wasm. :) 

If you are getting that error, that is most likely because you are trying to use the WASM object without running the JS bridge code first! There is an example in the base repo [here](https://github.com/teamortix/golang-wasm/tree/master/example/basic) That shows how it is done with webpack (loading the module first). This is needed to get things like the promise api and function bridging to work. If you are facing issues with getting this setup, please don't hesitate to reply and share some code :)

Best of luck
